---
abstract: 'PSGI Server implementation for POE'
author:
  - 'Paul Driver <frodwith@cpan.org>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-PSGI
requires:
  ExtUtils::MakeMaker: 6.11
  HTTP::Message::PSGI: 0
  HTTP::Status: 0
  POE: 0
  POE::Component::Server::TCP: 0
  POE::Filter::HTTP::Parser: 0
  Plack: 0
  Test::More: 0
  namespace::autoclean: 0
version: 0.5
